WITH CART_LIST AS (
    SELECT DISTINCT(CART_ID), NAME FROM CART_PRODUCTS
    WHERE NAME = 'Milk' OR NAME = 'Yogurt'
)


SELECT CART_ID FROM CART_LIST
# WHERE COUNT(CART_ID) >= 2
GROUP BY CART_ID
HAVING COUNT(CART_ID) >= 2


# SELECT * FROM CART_LIST