WITH FAVORITES_FOOD_TYPE AS (
    SELECT MAX(FAVORITES) AS MAX_FAVORITES, FOOD_TYPE FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES 
FROM REST_INFO AS A
JOIN FAVORITES_FOOD_TYPE AS B ON A.FOOD_TYPE = B.FOOD_TYPE
WHERE B.MAX_FAVORITES = A.FAVORITES
ORDER BY A.FOOD_TYPE DESC