WITH A AS
(SELECT CAR_ID, 
CASE WHEN START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16' THEN 1
ELSE 0 END AS AVA
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC)
# GROUP BY CAR_ID

SELECT CAR_ID, 
CASE WHEN SUM(AVA) > 0 THEN '대여중'
ELSE '대여 가능' END AS AVAILABILITY FROM A
GROUP BY CAR_ID
ORDER BY CAR_ID DESC