WITH HEAVY_USERS AS (
    SELECT HOST_ID, COUNT(HOST_ID) AS CNT FROM PLACES
    GROUP BY HOST_ID
)

SELECT ID, NAME, HOST_ID FROM PLACES
WHERE HOST_ID IN (SELECT HOST_ID FROM HEAVY_USERS WHERE CNT >= 2)