WITH RECURSIVE ALL_HOUR AS (
    SELECT 0 HOUR
    UNION
    SELECT HOUR+1 FROM ALL_HOUR WHERE HOUR < 23
), ANIMAL_OUTS_HOUR AS (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT FROM ANIMAL_OUTS
    GROUP BY HOUR
)

SELECT A.HOUR, IFNULL(B.COUNT, 0) AS COUNT FROM ALL_HOUR AS A
LEFT OUTER JOIN ANIMAL_OUTS_HOUR AS B ON A.HOUR = B.HOUR
GROUP BY A.HOUR
ORDER BY A.HOUR
