WITH TMP AS (
    SELECT B.USER_ID, B.NICKNAME 
    , SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD AS A 
    JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
    WHERE A.STATUS = 'DONE'
    GROUP BY B.USER_ID
)

SELECT * FROM TMP
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES