WITH COUNT_REVIEW AS
(SELECT COUNT(REVIEW_ID) AS CNT, MEMBER_ID FROM REST_REVIEW
GROUP BY MEMBER_ID)

SELECT A.MEMBER_NAME, B.REVIEW_TEXT
, DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS A
JOIN REST_REVIEW AS B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN ( SELECT MEMBER_ID FROM COUNT_REVIEW
                   WHERE CNT = (SELECT MAX(CNT) FROM COUNT_REVIEW) )
ORDER BY B.REVIEW_DATE, B.REVIEW_TEXT