WITH SUM_RECORDS AS (
SELECT  CAR_ID, COUNT(CAR_ID) AS TOTAL_RECORDS_COUNT 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
GROUP BY CAR_ID
)

SELECT MONTH(START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
# ,TOTAL_RECORDS_COUNT
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
JOIN SUM_RECORDS AS B ON A.CAR_ID = B.CAR_ID
WHERE TOTAL_RECORDS_COUNT >= 5 AND (MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10)
GROUP BY A.CAR_ID, MONTH
ORDER BY MONTH ASC, A.CAR_ID DESC