WITH A AS (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) AS DIFFERENTIATION_YEAR FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT DIFFERENTIATION_YEAR AS YEAR, ABS(MAX_SIZE_OF_COLONY - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA
JOIN A  
ON DIFFERENTIATION_YEAR = YEAR(DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV

