WITH MAX_PRICE_CATEGORY AS (
    SELECT MAX(PRICE) AS MAX_PRICE, CATEGORY FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)

SELECT A.CATEGORY, A.PRICE AS MAX_PRICE, A.PRODUCT_NAME FROM FOOD_PRODUCT AS A
JOIN MAX_PRICE_CATEGORY AS B ON A.CATEGORY = B.CATEGORY 
WHERE A.CATEGORY IN ( '과자', '국', '김치', '식용유' )
AND A.PRICE = B.MAX_PRICE
ORDER BY A.PRICE DESC

# SELECT * FROM FOOD_PRODUCT ORDER BY CATEGORY